<h2><i class="fa fa-user"></i> Création d'un compte client</h2>

<form data-validation class="generic-form" action="<?= $requestUrl ?>/user" method="POST">

	<?php if(empty($errorMessage) == false): ?>
		<aside class="error-message">
			<h3><i class="fa fa-warning"></i> Il y a <span id="total-error-count">1</span> erreur(s) dans le formulaire !</h3>
			<p><?= $errorMessage ?></p>
		</aside>
	<?php endif; ?>

	<fieldset>
		<legend><i class="fa fa-book"></i> Identité et coordonnées</legend>
		<ul>
			<li>
				<label for="lastName">Nom :</label>
				<input id="lastName" type="text" name="lastName" value="<?= $lastName ?>">
			</li>
			<li>
				<label for="firstName">Prénom :</label>
				<input id="firstName" type="text" name="firstName" value="<?= $firstName ?>">
			</li>
			<li>
				<label for="birthDay">Date de naissance :</label>
				<select id="birthDay" name="birthDay">
					<?php for($day = 1; $day <= 31; $day++): ?>
						<option value="<?= $day ?>"><?= $day ?></option>
					<?php endfor; ?>
				</select>
				<span> / </span>
				<select name="birthMonth">
					<option value="1">Janvier</option>
					<option value="2">Février</option>
					<option value="3">Mars</option>
					<option value="4">Avril</option>
					<option value="5">Mai</option>
					<option value="6">Juin</option>
					<option value="7">Juillet</option>
					<option value="8">Août</option>
					<option value="9">Septembre</option>
					<option value="10">Octobre</option>
					<option value="11">Novembre</option>
					<option value="12">Décembre</option>
				</select>
				<span> / </span>
				<select name="birthYear">
	                <?php for($year = 1940; $year <= date('Y') - 18; $year++): ?>
	                    <option value="<?= $year; ?>"><?= $year; ?></option>
	                <?php endfor; ?>
				</select>
			</li>
			<li>
				<label class="textarea" for="address">Adresse :</label>
				<textarea id="address" name="address" rows="3"><?= $address ?></textarea>
			</li>
			<li>
				<label for="city">Ville :</label>
				<input id="city" type="text" name="city" value="<?= $city ?>">
			</li>
			<li>
				<label for="zipCode">Code Postal :</label>
				<input id="zipCode" class="zip-code" type="text" name="zipCode" value="<?= $zipCode ?>">
			</li>
			<li>
				<label for="country">Pays :</label>
				<input id="country" class="country" type="text" name="country" value="<?= $country ?>">
			</li>
			<li>
				<label for="phone">Téléphone :</label>
				<input id="phone" class="phone" type="text" name="phone" value="<?= $phone ?>">
			</li>
		</ul>
	</fieldset>

	<fieldset>
		<legend><i class="fa fa-lock"></i> Informations d'authentification</legend>
		<ul>
	        <li>
	            <label for="email">E-mail :</label>
	            <input id="email" type="text" name="email"  value="<?= $email ?>">
	        </li>
	        <li>
	            <label for="password">Mot de passe :</label>
	            <input id="password" type="password" name="password">
	        </li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Créer le compte">
			<a class="button button-cancel" href="<?= $requestUrl ?>">Annuler</a>
		</li>
	</ul>
</form>